### ISSUE TITLE
Synedit

### ISSUE THREAD

**Issue by Alexey-T** [t-edson/PicPas#1]
Hi again. You could make the PicPas on ATsynedit, and then make better lexer for pascal for pic (it is easy to make lexer, no code)

**Comment by t-edson** [comment]
Hi Alex.
I didn't know, ATsynedit had a lexer. Where can I find information?

**Comment by Alexey-T** [comment]
You can see CudaText. it uses ATsynedit with 20 preinstalled lexers. I can make lexer for pic pascal

**Comment by t-edson** [comment]
It would be interesting see a lexer on ATsynedit for PicPas. But the idea of the design in PicPas is to be simple. Simple, because use libraries in layers:  SynFaci

**Comment by t-edson** [comment]
It will be necessary to exist some equivalent to t-Xpres for ATsynedit. It could be developed, of course, but I'm not so familiar with ATsynedit. Maybe later, I will port some code to ATsynedit. I think I would start using it, in some project who need an editor, an editor with the features that ATsynedit can offer and SynEdit not.

**Comment by Alexey-T** [comment]
I see, okay. Later create new issue (GH) and post 2-3 example fls (of PicPas), so i create hiliter

**Comment by t-edson** [comment]
Good. I will create a new document defining the language of PicPas. It's going to change to follow the Modula-2 style.

**Comment by Alexey-T** [comment]
Not document- just example files, i use examples

**Comment by Alexey-T** [comment]
PicPas is only in your program, other apps use it too?

**Comment by t-edson** [comment]
Well, I will prepare some examples. PicPas is still in development.  I don't know about other programs using PicPas.  I know about some people using SynFacilSyn, SynFacilCompletion, and even t-Xpress, but not about PicPas.
