### ISSUE TITLE
Instruccion org y delay_ms() / posible implementación de procedimiento especial para tratar interrupciones

### ISSUE THREAD

**Issue by AguHDz** [t-edson/PicPas#10]
Hola t-edson, acabo de codificar con éxito interrupciones usando un procedimiento al inicio del código Pascal y utilizando la instrucción org $0004 en ASM posición a la que como sabrás salta del contador de programa del PIC cuando se produce cualquier interrupción. El siguiente código funciona perfectamente: https://www.facebook.com/groups/electronicaymicrocontroladores/permalink/1679098122118937/
https://pastebin.com/PZqznLZB
pero si en algún lugar del programa utilizo la función del sistema delay_ms() su código sobrescribe cualquier otro código que usando la instrucción org se haya escrito al inicio del programa. Además, si por cualquier motivo usando la instrucción org deseamos que el programa se ejecute a partir de la dirección $0500, por ejemplo, porque se trate de un subprograma al que llamará algún tipo de firmware que nada tiene que ver con PicPas, si se usa delay_ms() el código siempre se incrusta a partir de la dirección $0002 por lo que no se puede utilizar en la práctica.

La solución creo que es muy sencilla, solo habría que colocar el código de delay_ms() o de cualquier otra función del sistema al final del código generado y no al principio y en una posición fija.

Por otro lado, a la vista del lo bien que parece funcionar la prueba que he realizado con las interrupciones y por lo fácil que me parece que resultaría implementarla simplemente usando un nombre de procedimiento reservado llamado por ejemplo `_ISR_`, creo que se podría incluir en la siguiente versión de PicPas. Simplemente hay que reservar ese u otro nombre para la interrupciones, el compilador añadir el código ASM al principio y a la salida del procedimiento, y compilarlo siempre ya que no existirá ninguna llamada en el programa. Yo he utilizado un truco para que la compilara, pero no creo que hiciera falta :)
```
//***********************************************************************
//  PROCEDIMIENTO: _ISR_
//  I.S.R. : Interrupt Service Routine (Rutina de Servicio a la Interrupcion)
//  Cualquier interrupcion producida en el uC 16F84A salta a la
//  direccion $0004, a partir de la que código de programa debe decidir
//  que hacer.
//***********************************************************************
procedure _ISR_;  // 
var
  Reg_W, Reg_STATUS : byte;  // Para guardar valores previos a interrupcion y restablecerlos antes de salir.
begin
ASM
;------------------------------------------------------------------------------------
; Posiciona la primera instruccion de interrupcion en la direccion $0004.
;------------------------------------------------------------------------------------
  org $0004
;------------------------------------------------------------------------------------
; Inicio de instrucciones que se ejecutan cuando se produce una interrupcion.
;------------------------------------------------------------------------------------
  MOVWF Reg_W        ; Guarda en registro W en Reg_W.
  SWAPF STATUS,w     ; Invierte los nibbles del registro de estado (STATUS) y lo guarda en W.
                     ; Se usa SWAPF en lugar de MOVF porque no afecta al flag Z del registro STATUS.
                     ; Es la tecnica recomendada por Microchip para salvaguardar los valores previos 
                     ; a la interrupcion.
  MOVWF Reg_STATUS   ; Guarda el contenido de W en Reg_STATUS.
;------------------------------------------------------------------------------------
END

  // INTERRUPCION TIMER TMR0 --------------------------------------------------------
  if (INTCON_T0IF = 1) then         // Comprueba si la interrupcion la ha producido el desbordamiento del TMR0.
    TMR0             := IniTMR0;    // Valor inicial de TMR0 para nueva cuenta.
    INTCON_T0IF      := 0;          // Restablece el valor del flag de deteccion de interrupcion TMR0.
    Inc(ContadorInTMR0);            // Incrementa contador de interrupciones
    if (ContadorInTMR0 = 4) then    // 4*(256-12)/(1e6/4/256) = 0,999424 segundos.      
      LED_1          := NOT LED_1;  // LED_1 invierte su valor.
      LED_2          := NOT LED_2;  // LED_2 invierte su valor.
      ContadorInTMR0 := 0;          // Se inicializa el contador de interrupciones.
    end;
  end; 
  // --------------------------------------------------------------------------------
  
ASM
;------------------------------------------------------------------------------------
; Fin de interrupcion y reposicion de los valores previos de W y STATUS.
;------------------------------------------------------------------------------------
  SWAPF Reg_STATUS,w ; Invertimos los nibbles para dejar en su posicion correcta el registro STATUS.
  MOVWF STATUS       ; Restauramos el valor de STATUS previo a la interrupcion.
  SWAPF Reg_W,f      ; Invertimos los nibbles de Reg_W y lo guardamos en la misma posicion de memoria.
  SWAPF Reg_W,w      ; Volvemos a invertor los nibbles de Reg_W y lo guardamos en el registro W, con
                     ; lo que queda con el valor que tenia antes de la interrupcion.
                     ; Se usa SWAPF en lugar de MOVF porque no afecta al flag Z del registro STATUS.
                     ; Es la tecnica recomendada por Microchip para salvaguardar los valores previos 
                     ; a la interrupcion.
  RETFIE             ; Retorna de la interrupcion.
;------------------------------------------------------------------------------------
END
end;
```
El código de aplicación completo : https://pastebin.com/PZqznLZB
Un video de la simulación en Proteus: https://www.facebook.com/groups/electronicaymicrocontroladores/permalink/1679098122118937/
Nuevas librerías:
PIC16F84A.pas : https://pastebin.com/i3PMcNGs
PIC16F877A.pas : https://pastebin.com/4eRdCPzA

**Comment by t-edson** [comment]
Para ubicar rutinas en posiciones absolutas, debería haber alguna sintaxis propia del Pascal de PicPas. No debería hacerse mediante bloques ASM.  
De momento, he creado los procedimientos de interrupción, que se compilan siempre en la posición 0x004. Puedes probarlo en la versión 0.7.1, que está publicado en forma experimental .
