### ISSUE TITLE
I want to say you some bug report, but i didnt find a way for that.

### ISSUE THREAD

**Issue by tikitatiktik** [t-edson/PicPas#19]
you have an error "for" loop and "while  TXSTA_TXEN = 0 do end; " . Those are very important. I want to inform you, if you are interest. Good luck. You will see when you have to try this command row for test.

**Comment by t-edson** [comment]
Hi. Could you please give more detail on the error. I can compile "while TXSTA_TXEN = 0 do end; " without problems.

**Comment by tikitatiktik** [comment]
Hi. You will see an error when you focus to highlighted lines on the picture.

picpas:

while  TXSTA_TRMT = 0 do end;

list file:

0x0DD btfsc RCSTA_OERR


"TXSTA" is converting to "RCSTA" .  Thanks for your interest. Have a nice day.

________________________________
Gönderen: Tito Hinostroza <notifications@github.com>
Gönderildi: 22 Kasım 2017 Çarşamba 14:35:47
Kime: t-edson/PicPas
Bilgi: tikitatiktik; Author
Konu: Re: [t-edson/PicPas] I want to say you some bug report, but i didnt find a way for that. (#19)


Hi. Could you please give more detail on the error. I can compile "while TXSTA_TXEN = 0 do end; " without problems.

**Comment by tikitatiktik** [comment]
![txsta_trmt](https://user-images.githubusercontent.com/32754291/33244448-59cdef56-d308-11e7-9e44-293f6e796952.png)

**Comment by t-edson** [comment]
I see. The code is compiled right. The assembler code is wrong. TXSTA and RCSTA share the same address but different RAM bank. The disassembler, have no way to know if the address 0x18 of the opcode btfsc, refers to teh bank0 or the bank1.
The compiler work well. It's just the assembler view is generated from the binary directly, where the bank address is lost.

**Comment by t-edson** [comment]
PicPas doesn't generate assembler code. It compiles directly to binary. That's the problem. Once binary created, there is not information about banks in opcodes, in the binary. It's an issue of the disassembler. 
I have considered to include some aditional information in the binary, to solve this problem, but it will take some time.
