### ISSUE TITLE
error variable initial value

### ISSUE THREAD

**Issue by alexpseletr** [t-edson/PicPas#21]
var 
contador:dword=0;

error

**Comment by t-edson** [comment]
No. In PicPas you cannot "declare and assign". 

The section VAR is only for declaractions. Maybe later PicPas implement this functionality.

**Comment by alexpseletr** [comment]
There is a project (http://www.pas2pic.hu ) that possibly facilitates development, it is at command prompt and has an array implementation, initial value of variables and others

I do not say that it is as good as an ideal that has developed but should help

**Comment by t-edson** [comment]
It looks a very basic compiler. And it's discontinued. Anyway, I will check.
