### ISSUE TITLE
source code compile

### ISSUE THREAD

**Issue by wshorbagy** [t-edson/PicPas#46]
Hello,
I am using lazarus v1.8.2 and try to compile the source code,
there are some missing units such as SynFacilUtils,MisUtils
please how to compile the source code?
thanks.

**Comment by t-edson** [comment]
Hi. You need to download all the libraries to compile. All of the libraries are in my GitHub too. 
But if you have problems there is a project including all the libraries: https://github.com/t-edson/PicPas/raw/0.8.5/temp/PicPas0.8.4.Full.rar
It's not the current version but can help if you want to test the code.

**Comment by wshorbagy** [comment]
Hi, i found the missing libraries available on your GitHub ,
i know taht after reading the README.md file and can compile now,
and its a good idea to collect all in one ,
many thanks ,
