### ISSUE TITLE
Missing some SET_STATE_RAM

### ISSUE THREAD

**Issue by Lulu04** [t-edson/PicPas#55]
Hi, 
Cuistax, you did a lot of work on PIC declaration files !
I have checked the PIC16F1825.pas in 'devices17' and it seems to miss  the SET_STATE_RAM declaration for the core registers in each bank. Only the INDF register is declared. The SET_MAPPED_RAM section semms to be well defined.

**Comment by cuistax** [comment]
Hello Lulu04 !

What file are you looking at ?

The latest version of the file is at [https://github.com/t-edson/PicPas/blob/0.8.7/devices17/PIC16F1825.pas](https://github.com/t-edson/PicPas/blob/0.8.7/devices17/PIC16F1825.pas)

The SET_STATE_RAM directives start at line 678.

Let me know if anything is missing.

**Comment by t-edson** [comment]
I can confirm it. If we look at the RAM explorer after compiling PIC16F1825.pas, we have:
![imagen](https://user-images.githubusercontent.com/7736802/41375224-05c60722-6f1b-11e8-8137-435395a55281.png)

It's some difficult to see 32 banks in one window, but it can be apreciate the upper bytes of banks 1 to 31 are unimplemented.
I need to include some kind of zoom for this window.

**Comment by cuistax** [comment]
Ok I understand the problem now, I will look into it.

By the way, may I suggest to add a legend to that nice window, so that we can understand what the different colors mean ? 

That would be extra nice !

Another suggestion I would make is to have a tooltip label that shows up as you move the mouse cursor over the different regions, telling what's inside the region. That would make that window even more  useful !

**Comment by cuistax** [comment]
Hi Lulu04,

The device units have been fixed here : #57, you can check it out.

Thanks for reporting this, and let us know if you spot any other issue.

**Comment by t-edson** [comment]
> By the way, may I suggest to add a legend to that nice window, so that we can understand what the different colors mean ?

It was planned having a legend. No time to implement before. I will check it now.

**Comment by Lulu04** [comment]
Hi Cuistax and Edson, Thanks to the fixes.
But now, I can't compile the device unit: the message 'Adress exceed limits of this device'.
I use the win64 version of PicPas 0.8.7

**Comment by cuistax** [comment]
Could you share your program ? Or, better, the smallest program that reproduces the issue ?
 
I tried the following (very simplistic) program on my side (a blinkled), it does not produce any error:
```pascal
{Sample program to blink a Led on PORTA.RA2}
program BlinkLed;
uses PIC16F1825;

begin
  TRISA := 0;   //all outputs
  while true do
    delay_ms(1000);
    PORTA_RA2 := not PORTA_RA2;
  end;
end.
```

**Comment by t-edson** [comment]
Legend added to the RAM explorer in 0.8.8.  No complete but it's an advance: 
![imagen](https://user-images.githubusercontent.com/7736802/41473069-db7aaaf4-707d-11e8-8a87-7faf0acfb2ee.png)

**Comment by t-edson** [comment]
> But now, I can't compile the device unit: the message 'Adress exceed limits of this device'.

This is a bug found in some units, and have two parts:
* Bad error location: FIXED. The error must appear in variabel declaration. Please update.
* Bad hardware limits defined in the compiler.

PIC17 compiler assumed the max Bank number for Enhanced Mid-range devices is 32 so address like $1E0F, are not allowed. 
Can someone tell me how is the max number of bank for the Enhanced Mid-range family? 32, 64, 128? This is some crazy.

**Comment by cuistax** [comment]
As of today, the maximum number of banks in any PIC is 64.

But, you may as well put the limit at 256, to be future proof (the BSR register will never be able to hold more than 8 bits ;).

The current list of models using 64 banks are (all in the Enhanced Mid Range):
PIC16F15313 PIC16F15323 PIC16F15324 PIC16F15325 PIC16F15344 PIC16F15345 
PIC16F15354 PIC16F15355 PIC16F15356 PIC16F15375 PIC16F15376 PIC16F15385 
PIC16F15386

PIC16F18424 PIC16F18425 PIC16F18426 PIC16F18444 PIC16F18445 PIC16F18446 
PIC16F18455 PIC16F18456 PIC16F18857 PIC16F18877

PIC16F19155 PIC16F19156 PIC16F19175 PIC16F19176 PIC16F19185 PIC16F19186 
PIC16F19195 PIC16F19196 PIC16F19197

**Comment by cuistax** [comment]
If you are to choose one model for testing the Enhanced Mid Range, I would recommend the PIC16F19197.

It's the biggest, craziest, most complex PIC in the range. 
The datasheet alone is 708 pages long !

If you have that one working, other models will too....

**Comment by t-edson** [comment]
OK. I prefer to set in 64 by now, because some variables in the compiler are resized to the max number of banks, so using 128 or 256 will waste memory.
The directives $SET_STATE_RAM and $SET_MAPPED_RAM must be updated too, to support bigger adresses. No a big problem.

**Comment by t-edson** [comment]
Some advances in automate test. An option has been added to the >Tools menu, to compile all the units in /device10, /device16 and /device17 fodlers.

**Comment by cuistax** [comment]
Strangely I get display issues on Mac:

![ram_explorer](https://user-images.githubusercontent.com/12441426/41498347-96ad7aa2-716b-11e8-8911-da29c3b1a426.png)

Also, some menus don't display correctly anymore, such as the compiler selection:

PicPas 0.8.7:
![picpas_8 7](https://user-images.githubusercontent.com/12441426/41498351-b0bc94f0-716b-11e8-92c3-757c5fc0a7af.png)

PicPas 0.8.8:
![picpas_8 8](https://user-images.githubusercontent.com/12441426/41498352-b983612c-716b-11e8-8042-8c7ab7917668.png)

Could it be that some source files were not uploaded to Github ?

**Comment by t-edson** [comment]
I think it's a problem of the translation files, was outdated.  Please update now. The RAM Explorer has been modified too.
Moreover, the directive $SET_STATE_RAM, can accept now, one more parameter:

```
//Set state for all banks
{$SET_STATE_RAM '000-00C:SFR:ALL'}  
//Set state for all banks and map them to bank 0
{$SET_STATE_RAM '000-00C:SFR:ALLMAPPED'}
```
So we can  simplify the units.

**Comment by cuistax** [comment]
Hi,

The Device Units have been updated to take advantage of the new syntax.
You can check them out here :  #58 

Cheers,
